events {}

http {
  upstream backend_cluster {
    server backend-1:8080;
    server backend-2:8080;
    server backend-3:8080;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend_cluster;
    }

    location / {
      proxy_pass http://frontend;
    }
  }
}